//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oforadata.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class basket
    {
        public int id { get; set; }
        public int pid { get; set; }
        public int uid { get; set; }
        public System.DateTime date { get; set; }
        public decimal price { get; set; }
        public int basketId { get; set; }
        public Nullable<int> onay { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<int> odeme { get; set; }
    
        public virtual product product { get; set; }
        public virtual User User { get; set; }
    }
}
