//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oforadata.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int id { get; set; }
        public string folderName { get; set; }
        public int pid { get; set; }
        public string folderName1 { get; set; }
        public string folderName2 { get; set; }
    
        public virtual product product { get; set; }
    }
}
